[ScanPro-Inbox]
   path = /var/lib/scanpro/inbox
   browseable = yes
   read only = no
   guest ok = no
   valid users = scanpro
   force user = scanpro
   create mask = 0660
   directory mask = 0770

[ScanPro-Jobs]
   path = /var/lib/scanpro/jobs
   browseable = yes
   read only = yes
   guest ok = no
   valid users = scanpro
   force user = scanpro
