import json
import re
import subprocess
from pathlib import Path

from sqlalchemy.orm import Session

from ..db import DATA_ROOT
from ..models import Destination, ScanInput

SAMBA_CONFIG = DATA_ROOT / "samba-inputs.conf"
INPUT_ROOT = DATA_ROOT / "Eingang"
OUTPUT_ROOT = DATA_ROOT / "Ausgang"
SAMBA_HELPER = "/usr/local/sbin/scanpro-samba-user"


class ShareError(RuntimeError):
    pass


def normalize_share_name(value: str) -> str:
    value = value.strip()
    if not value:
        raise ShareError("Freigabename darf nicht leer sein.")
    if len(value) > 80:
        raise ShareError("Freigabename darf maximal 80 Zeichen haben.")
    if not re.fullmatch(r"[A-Za-z0-9ÄÖÜäöüß._ -]+", value):
        raise ShareError("Freigabename enthält ungültige Zeichen.")
    return value


def input_path(input_id: int, share_name: str | None = None) -> Path:
    folder = (share_name or str(input_id)).strip() or str(input_id)
    path = INPUT_ROOT / folder
    path.mkdir(parents=True, exist_ok=True)
    return path


def ensure_samba_username_available(username: str) -> None:
    result = subprocess.run(
        ["sudo", SAMBA_HELPER, "check-available", username],
        text=True, capture_output=True, timeout=15,
    )
    if result.returncode:
        raise ShareError(result.stderr.strip() or "SMB-Benutzername ist bereits belegt.")


def set_samba_password(username: str, password: str) -> None:
    result = subprocess.run(
        ["sudo", SAMBA_HELPER, "set-password", username],
        input=password + "\n",
        text=True,
        capture_output=True,
        timeout=15,
    )
    if result.returncode != 0:
        raise ShareError(result.stderr.strip() or "Samba-Benutzer konnte nicht aktualisiert werden.")


def prepare_input_folder(username: str, path: Path) -> None:
    result = subprocess.run(
        ["sudo", SAMBA_HELPER, "prepare-input", username, str(path)],
        text=True,
        capture_output=True,
        timeout=15,
    )
    if result.returncode != 0:
        raise ShareError(result.stderr.strip() or "Eingangsordner konnte nicht vorbereitet werden.")


def output_path(name: str) -> Path:
    path = OUTPUT_ROOT / normalize_share_name(name)
    path.mkdir(parents=True, exist_ok=True)
    return path


def prepare_output_folder(username: str, path: Path) -> None:
    result = subprocess.run(
        ["sudo", SAMBA_HELPER, "prepare-output", username, str(path)],
        text=True,
        capture_output=True,
        timeout=15,
    )
    if result.returncode != 0:
        raise ShareError(result.stderr.strip() or "Ausgangsordner konnte nicht vorbereitet werden.")


def delete_samba_user(username: str) -> None:
    if not username:
        return
    try:
        subprocess.run(
            ["sudo", SAMBA_HELPER, "delete", username],
            check=False,
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired):
        pass


def sync_samba_config(db: Session) -> None:
    DATA_ROOT.mkdir(parents=True, exist_ok=True)
    INPUT_ROOT.mkdir(parents=True, exist_ok=True)
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    try:
        INPUT_ROOT.chmod(0o755)
        OUTPUT_ROOT.chmod(0o755)
    except OSError:
        pass

    input_rows = db.query(ScanInput).filter(ScanInput.enabled.is_(True)).order_by(ScanInput.id).all()
    input_users = []
    for row in input_rows:
        if not row.smb_username:
            continue
        path = input_path(row.id, row.share_name)
        prepare_input_folder(row.smb_username, path)
        row.path = str(path)
        input_users.append(row.smb_username)

    output_rows = db.query(Destination).filter(
        Destination.type == "local_smb",
        Destination.enabled.is_(True),
    ).order_by(Destination.id).all()
    output_users = []
    for row in output_rows:
        try:
            cfg = json.loads(row.config_json or "{}")
        except Exception:
            cfg = {}
        username = str(cfg.get("username", "")).strip()
        if not username:
            continue
        path = output_path(row.name)
        prepare_output_folder(username, path)
        output_users.append(username)

    blocks = ["# Generated by ScanPro", "# Do not edit manually.", ""]
    if input_users:
        blocks += [
            "[Eingang]",
            f"    path = {INPUT_ROOT}",
            "    browseable = yes",
            "    read only = no",
            "    guest ok = no",
            f"    valid users = {' '.join(input_users)}",
            "    hide unreadable = yes",
            "    access based share enum = yes",
            "    create mask = 0660",
            "    directory mask = 0770",
            "",
        ]

    if output_users:
        blocks += [
            "[Ausgang]",
            f"    path = {OUTPUT_ROOT}",
            "    browseable = yes",
            "    read only = no",
            "    guest ok = no",
            f"    valid users = {' '.join(output_users)}",
            "    hide unreadable = yes",
            "    access based share enum = yes",
            "    create mask = 0660",
            "    directory mask = 0770",
            "",
        ]

    db.commit()
    SAMBA_CONFIG.write_text("\n".join(blocks), encoding="utf-8")

def reload_samba() -> None:
    try:
        subprocess.run(["systemctl", "reload", "smbd"], check=False, timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        pass
