import re
import subprocess
from pathlib import Path

from sqlalchemy.orm import Session

from ..db import DATA_ROOT
from ..models import ScanInput

SAMBA_CONFIG = DATA_ROOT / "samba-inputs.conf"
INPUT_ROOT = DATA_ROOT / "inputs"
SAMBA_HELPER = "/usr/local/sbin/scanpro-samba-user"


class ShareError(RuntimeError):
    pass


def normalize_share_name(value: str) -> str:
    value = value.strip()
    if not value:
        raise ShareError("Freigabename darf nicht leer sein.")
    if len(value) > 80:
        raise ShareError("Freigabename darf maximal 80 Zeichen haben.")
    if not re.fullmatch(r"[A-Za-z0-9ÄÖÜäöüß._ -]+", value):
        raise ShareError("Freigabename enthält ungültige Zeichen.")
    return value


def input_path(input_id: int) -> Path:
    path = INPUT_ROOT / str(input_id)
    path.mkdir(parents=True, exist_ok=True)
    return path


def set_samba_password(username: str, password: str) -> None:
    result = subprocess.run(
        ["sudo", SAMBA_HELPER, "set-password", username],
        input=password + "\n",
        text=True,
        capture_output=True,
        timeout=15,
    )
    if result.returncode != 0:
        raise ShareError(result.stderr.strip() or "Samba-Benutzer konnte nicht aktualisiert werden.")


def delete_samba_user(username: str) -> None:
    if not username:
        return
    try:
        subprocess.run(
            ["sudo", SAMBA_HELPER, "delete", username],
            check=False,
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired):
        pass


def sync_samba_config(db: Session) -> None:
    DATA_ROOT.mkdir(parents=True, exist_ok=True)
    INPUT_ROOT.mkdir(parents=True, exist_ok=True)
    rows = db.query(ScanInput).filter(ScanInput.enabled.is_(True)).order_by(ScanInput.id).all()
    blocks = ["# Generated by ScanPro 1.1-dev", "# Do not edit manually.", ""]
    for row in rows:
        if not row.smb_username:
            continue
        path = input_path(row.id)
        row.path = str(path)
        blocks += [
            f"[{row.share_name}]",
            f"    path = {path}",
            "    browseable = yes",
            "    read only = no",
            "    guest ok = no",
            f"    valid users = {row.smb_username}",
            "    force user = scanpro",
            "    create mask = 0660",
            "    directory mask = 0770",
            "",
        ]
    db.commit()
    SAMBA_CONFIG.write_text("\n".join(blocks), encoding="utf-8")


def reload_samba() -> None:
    try:
        subprocess.run(["systemctl", "reload", "smbd"], check=False, timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        pass
